export const SET_USERS = "SET_USERS";
export const SET_SELECTED_USER_ID = "SET_SELECTED_USER_ID";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const UPDATE_SELECTED_USER = "UPDATE_SELECTED_USER";
